### ISSUE TITLE
Update for Bolt 3 compatibility

### ISSUE THREAD

**Issue by royallthefourth** [royallthefourth/CodeHighlightBolt#4]

**Comment by michaelborn** [comment]
@royallthefourth What is left in this? Was commit 8dcc77ff83a9e83116daee1b1867cfcd25378249 unable to resolve this?

**Comment by michaelborn** [comment]
Also note that this extension has an [out-of-date version](https://github.com/royallthefourth/CodeHighlightBolt/tree/1.0.4) listed on the [Bolt Marketplace](https://market.bolt.cm/view/royallthefourth/codehighlightbolt). `1.0.4` does not include the latest Bolt 3 compat updates made in https://github.com/royallthefourth/CodeHighlightBolt/commit/8dcc77ff83a9e83116daee1b1867cfcd25378249.

I believe pushing a `1.0.5` or perhaps `1.1.0` git tag would be appropriate, then please update the marketplace package to pull the latest version. Thanks!

**Comment by royallthefourth** [comment]
v1.0.4 is the latest release. I didn't tag a newer release because, as I recall, the current state of this repo failed on a Bolt 3.0 pre-release version. There was no output at all and I didn't feel like dealing with that at the time. I'll give it another shot this weekend and see if I can get a working version of this on the latest release.

**Comment by royallthefourth** [comment]
Trying to install `head` locally doesn't work at all. It doesn't appear in the extensions list, even after I regenerate the extension autoloader. Not sure what I'm doing wrong there.

After switching to `minimum-stability: "dev"` in the extensions dir, I am at least able to install it from the GUI. Apparently I had implemented a `final` method and caused a fatal error.

**Comment by royallthefourth** [comment]
Woops, missed your PR. Sorry.

**Comment by michaelborn** [comment]
@royallthefourth Sorry about that! Yeah, with my PR I was able to get it running perfectly on Bolt `3.5.7`.

**Comment by royallthefourth** [comment]
Time to tag

**Comment by michaelborn** [comment]
Thanks!
